var emociones = {
    "cell1":"Enfurecido",
    "cell2":"Aterrado",
    "cell3":"Estresado",
    "cell4":"Inquieto",
    "cell5":"Impactado",
    "cell6":"Sorprendido",
    "cell7":"Encantado",
    "cell8":"Festivo",
    "cell9":"Eufórico",
    "cell10":"Extasiado",
    "cell11":"Desesperado",
    "cell12":"Furioso",
    "cell13":"Frustrado",
    "cell14":"Tenso",
    "cell15":"Atónito",
    "cell16":"Hiperactivo",
    "cell17":"Jovial",
    "cell18":"Motivado",
    "cell19":"Inspirado",
    "cell20":"Exultante",
    "cell21":"Exasperado",
    "cell22":"Asustado",
    "cell23":"Enojado",
    "cell24":"Nervioso",
    "cell25":"Inquieto",
    "cell26":"Energético",
    "cell27":"Animado",
    "cell28":"Emocionado",
    "cell29":"Optimista",
    "cell30":"Entusiasta",
    "cell31":"Ansioso",
    "cell32":"Aprensivo",
    "cell33":"Preocupado",
    "cell34":"Irritado",
    "cell35":"Enojado",
    "cell36":"Complacido",
    "cell37":"Centrado",
    "cell38":"Feliz",
    "cell39":"Orgulloso",
    "cell40":"Ilusionado",
    "cell41":"Indignado",
    "cell42":"Afligido",
    "cell43":"Afectado",
    "cell44":"Intranquilo",
    "cell45":"Molesto",
    "cell46":"Agradable",
    "cell47":"Alegre",
    "cell48":"Esperanzado",
    "cell49":"Juguetón",
    "cell50":"Dichoso",
    "cell51":"Rechazado",
    "cell52":"Taciturno",
    "cell53":"Decepcionado",
    "cell54":"Decaído",
    "cell55":"Apático",
    "cell56":"A gusto",
    "cell57":"Despreocupado",
    "cell58":"Contento",
    "cell59":"Amoroso",
    "cell60":"Realizado",
    "cell61":"Pesimista",
    "cell62":"Malhumorado",
    "cell63":"Desanimado",
    "cell64":"Triste",
    "cell65":"Aburrido",
    "cell66":"Calmado",
    "cell67":"Seguro",
    "cell68":"Satisfecho",
    "cell69":"Agradecido",
    "cell70":"Conmovido",
    "cell71":"Enajenado",
    "cell72":"Infeliz",
    "cell73":"Desanimado",
    "cell74":"Triste",
    "cell75":"Aburrido",
    "cell76":"Relajado",
    "cell77":"Distendido",
    "cell78":"Descansado",
    "cell79":"Afortunado",
    "cell80":"Equilibrado",
    "cell81":"Desalentado",
    "cell82":"Deprimido",
    "cell83":"Huraño",
    "cell84":"Exhausto",
    "cell85":"Fatigado",
    "cell86":"Apacible",
    "cell87":"Reflexivo",
    "cell88":"En paz",
    "cell89":"Cómodo",
    "cell90":"Desenfadado",
    "cell91":"Devastado",
    "cell92":"Desesperanzado",
    "cell93":"Desolado",
    "cell94":"Consumido",
    "cell95":"Agotado",
    "cell96":"Soñoliento",
    "cell97":"Complaciente",
    "cell98":"Tranquilo",
    "cell99":"Afable",
    "cell100":"Sereno"
};
var causas = {
    "cell1":"Te sientes enfurecido cuando percibes una amenaza a tus valores, intereses o expectativas. Puede ser una reacción a la frustración o injusticia, activando una respuesta intensa de defensa.",
    "cell2":"El miedo extremo o terror surge ante la percepción de un peligro inminente que amenaza tu seguridad física o emocional, activando tu instinto de supervivencia.",
    "cell3":"El estrés ocurre cuando te enfrentas a presiones o demandas que parecen superar tus recursos personales, provocando tensión y preocupación.",
    "cell4":"La inquietud puede surgir cuando estás anticipando un evento importante o preocupante, o cuando sientes que no tienes control sobre una situación.",
    "cell5":"Sentirse impactado es una respuesta natural a eventos inesperados o traumáticos que rompen tu sentido de normalidad.",
    "cell6":"La sorpresa se produce ante eventos inesperados o información nueva que no se anticipaba, lo cual puede ser emocionante y estimulante.",
    "cell7":"El encanto surge cuando experimentas placer, belleza o una cualidad excepcional en algo o alguien, despertando admiración y satisfacción.",
    "cell8":"La emoción festiva se activa en ambientes de celebración o durante eventos especiales que involucran socialización y alegría compartida.",
    "cell9":"La euforia generalmente ocurre en respuesta a un éxito extraordinario o una experiencia sumamente gratificante, superando las expectativas.",
    "cell10":"El éxtasis se experimenta cuando alcanzas un pico de alegría y satisfacción, a menudo durante momentos de logro o conexión profunda.",
    "cell11":"La desesperación suele aparecer cuando sientes que no hay salida a una situación difícil o cuando las soluciones intentadas no han funcionado.",
    "cell12":"La furia puede ser causada por sentir que tus límites han sido violados o que has sido tratado injustamente.",
    "cell13":"La frustración aparece cuando tus esfuerzos no producen los resultados esperados o cuando enfrentas obstáculos que impiden alcanzar tus metas.",
    "cell14":"La tensión puede ser resultado de estrés prolongado, preocupaciones constantes o anticipación de posibles problemas.",
    "cell15":"Sentirse atonito suele ocurrir frente a eventos inesperados o información sorprendente que desafía tu comprensión del mundo.",
    "cell16":"La hiperactividad emocional puede surgir cuando estás muy estimulado o entusiasmado por una actividad o situación, lo que lleva a un exceso de energía y motivación.",
    "cell17":"La jovialidad surge en situaciones de interacción social alegre, donde el humor y la camaradería elevan tu estado de ánimo.",
    "cell18":"La motivación a menudo se enciende cuando tienes objetivos claros y alcanzables, y cuando sientes que tus acciones pueden llevar a resultados exitosos.",
    "cell19":"La inspiración suele surgir cuando te encuentras con personas, ideas, arte o naturaleza que te mueven profundamente, encendiendo tu creatividad y deseo de expresión.",
    "cell20":"La exultación ocurre durante los momentos de gran triunfo o cuando se superan significativos desafíos, ofreciendo una sensación intensa de satisfacción y victoria.",
    "cell21":"La exasperación surge cuando te enfrentas repetidamente a las mismas dificultades sin encontrar una solución efectiva.",
    "cell22":"El miedo intenso o estar asustado puede surgir en situaciones de amenaza real o percibida, activando tu instinto de supervivencia.",
    "cell23":"El enojo puede ser provocado por sentirse herido, ofendido o cuando algo va contra tus expectativas o principios.",
    "cell24":"El nerviosismo generalmente aparece en situaciones de incertidumbre o cuando te enfrentas a un nuevo desafío.",
    "cell25":"Sentirse inquieto puede resultar de un deseo de cambio o progreso que no se está cumpliendo, generando una sensación de estancamiento o frustración.",
    "cell26":"Sentirse energético puede resultar de un bienestar físico y mental, así como de la anticipación positiva de eventos o actividades que te entusiasman.",
    "cell27":"La sensación de estar animado surge en ambientes positivos y estimulantes, donde la interacción y la actividad son placenteras y divertidas.",
    "cell28":"La emoción surge cuando anticipas algo deseado o cuando estás a punto de experimentar algo nuevo y emocionante.",
    "cell29":"El optimismo generalmente se origina en una visión positiva de la vida y en la creencia de que las cosas mejorarán o se resolverán favorablemente.",
    "cell30":"El entusiasmo puede ser desencadenado por intereses apasionados, proyectos emocionantes o eventos que alinean perfectamente con tus valores y objetivos.",
    "cell31":"La ansiedad puede surgir ante la anticipación de un evento futuro incierto o preocupante, creando una sensación de temor o aprehensión.",
    "cell32":"La aprensión se siente ante la expectativa de que algo malo pueda suceder, basada en experiencias pasadas o miedos internos.",
    "cell33":"La preocupación surge cuando te concentras en problemas futuros o posibles consecuencias negativas de situaciones actuales.",
    "cell34":"La irritación a menudo ocurre en respuesta a molestias menores o cuando las personas o situaciones no cumplen con tus expectativas.",
    "cell35":"Sientes enojo cuando percibes una amenaza a tu bienestar o justicia personal, o cuando tus límites personales son violados.",
    "cell36":"Sentirse complacido generalmente resulta de la satisfacción con los resultados obtenidos o del placer derivado de una experiencia positiva que cumple o supera las expectativas.",
    "cell37":"Sentirse centrado surge de un estado de equilibrio y armonía interior, donde te sientes en control de tus emociones y alineado con tus valores y objetivos.",
    "cell38":"La felicidad es una respuesta emocional a experiencias agradables, logros, o la conexión significativa con otras personas.",
    "cell39":"El orgullo surge de logros personales o del éxito de personas cercanas a ti, reflejando un reconocimiento de esfuerzo y competencia.",
    "cell40":"La ilusión se experimenta cuando anticipas futuros positivos o emocionantes, llenos de posibilidades y esperanzas.",
    "cell41":"La indignación surge cuando percibes una injusticia o un trato deshonesto o inmoral hacia ti o hacia otros.",
    "cell42":"La aflicción surge en respuesta a pérdidas significativas o situaciones desalentadoras que impactan profundamente tu estado emocional.",
    "cell43":"Estar afectado puede ser resultado de recibir noticias impactantes, enfrentarse a cambios abruptos o experimentar eventos traumáticos.",
    "cell44":"La inquietud se manifiesta cuando estás preocupado por problemas sin resolver o cuando anticipas dificultades futuras.",
    "cell45":"Sentirse molesto puede originarse por interrupciones, comportamientos irritantes de otras personas o situaciones que no cumplen con tus expectativas.",
    "cell46":"Sentirse agradable suele resultar de interacciones armoniosas, experiencias placenteras o la satisfacción de estar en un entorno cómodo y acogedor.",
    "cell47":"La alegría emerge de experiencias que generan placer, satisfacción o diversión, y puede ser estimulada por logros, celebraciones o simplemente disfrutar de la vida cotidiana.",
    "cell48":"La esperanza se siente cuando hay una expectativa optimista sobre el futuro o la creencia en la posibilidad de resultados positivos frente a las adversidades.",
    "cell49":"La sensación de ser juguetón a menudo surge en ambientes relajados y seguros donde puedes explorar, experimentar y disfrutar sin miedo a las críticas o consecuencias.",
    "cell50":"Sentirse dichoso es una intensa experiencia de completa felicidad y satisfacción, a menudo resultante de vivir un momento o situación que se alinea perfectamente con lo que más valoras y disfrutas.",
    "cell51":"El sentimiento de rechazo suele surgir cuando te sientes excluido o no aceptado por otros, lo que puede afectar profundamente tu autoestima y sentido de pertenencia.",
    "cell52":"La taciturnidad puede ser causada por pensamientos profundos o preocupaciones, y se manifiesta como un estado de quietud y silencio.",
    "cell53":"La decepción surge cuando las expectativas o esperanzas no se cumplen, ya sea por situaciones o por acciones de otras personas.",
    "cell54":"Sentirse decaído puede resultar de la fatiga, el desgaste emocional o la desilusión después de eventos desafiantes o desalentadores.",
    "cell55":"La apatía a menudo se desarrolla en situaciones donde sientes que tus esfuerzos son infructuosos o cuando te desconectas emocionalmente de tus actividades y relaciones.",
    "cell56":"Sentirse a gusto suele provenir de estar en un entorno o situación que satisface tus necesidades y deseos personales, sin presiones o preocupaciones inmediatas.",
    "cell57":"La despreocupación a menudo resulta de una liberación temporal de responsabilidades o preocupaciones, permitiéndote disfrutar del momento presente sin estrés.",
    "cell58":"Estar contento generalmente proviene de sentirse satisfecho con tus logros, tu vida personal o simplemente disfrutar de las pequeñas alegrías diarias.",
    "cell59":"Sentimientos amorosos surgen de conexiones profundas y significativas con otras personas, mascotas o incluso actividades que te llenan de afecto y aprecio.",
    "cell60":"La sensación de realización viene de alcanzar metas significativas, de vivir de acuerdo con tus valores o de contribuir de manera positiva a la vida de otros.",
    "cell61":"El pesimismo puede surgir de experiencias pasadas negativas o de una tendencia a enfocarse en los aspectos más desfavorables de las situaciones, anticipando resultados negativos.",
    "cell62":"La malhumor se puede desencadenar por estrés, cansancio, hambre o frustración acumulada, y se manifiesta en irritabilidad y propensión a la frustración.",
    "cell63":"El desánimo puede ocurrir cuando enfrentas repetidos fracasos o cuando los obstáculos parecen insuperables, minando tu motivación y esperanza.",
    "cell64":"La tristeza es una respuesta natural a pérdidas, decepciones o cambios significativos en la vida. También puede surgir de la empatía por el sufrimiento de otros.",
    "cell65":"El aburrimiento suele aparecer cuando te encuentras en situaciones que consideras monótonas o carentes de estímulo, o cuando no estás suficientemente desafiado.",
    "cell66":"La calma suele ser el resultado de un entorno sin estrés, la ausencia de conflictos y la sensación de que las necesidades personales están siendo satisfechas.",
    "cell67":"Sentirse seguro a menudo se deriva de un entorno estable, predecible y de confianza en uno mismo y en los que te rodean.",
    "cell68":"La satisfacción generalmente viene de cumplir metas, de la armonía en tus relaciones personales, o de vivir en congruencia con tus valores.",
    "cell69":"La gratitud surge al reconocer y apreciar los beneficios que recibes, ya sea a través de las acciones de otras personas, circunstancias favorables, o incluso la apreciación de los aspectos simples de la vida.",
    "cell70":"Suele surgir al presenciar actos de bondad, belleza artística o expresiones genuinas de emociones humanas que resuenan contigo a un nivel profundo.",
    "cell71":"La sensación de enajenación puede surgir cuando te sientes desconectado de tu entorno social o laboral, o cuando percibes que tus valores o necesidades no están alineados con los de tu grupo.",
    "cell72":"La infelicidad puede ser el resultado de una serie de situaciones que no cumplen con tus expectativas o deseos, ya sea en relaciones, trabajo, o aspectos personales.",
    "cell73":"Además de la causa mencionada anteriormente, el desánimo también puede provenir de la falta de reconocimiento o aprecio por tus esfuerzos.",
    "cell74":"Como se mencionó antes, además de las pérdidas y cambios, la tristeza puede surgir de la falta de conexión o satisfacción en las relaciones personales.",
    "cell75":"Adicionalmente, el aburrimiento puede ser un síntoma de depresión o de no sentirse desafiado suficientemente en áreas importantes de la vida.",
    "cell76":"La relajación suele resultar de estar en un ambiente tranquilo, sentirse seguro, y no tener demandas inmediatas que atender.",
    "cell77":"Sentirse distendido es a menudo resultado de la liberación de tensiones y la sensación de que no hay urgencias que requieran tu atención.",
    "cell78":"Estar descansado es el resultado de obtener un sueño reparador y permitirse pausas adecuadas entre las actividades demandantes.",
    "cell79":"La sensación de fortuna surge al reconocer y apreciar las circunstancias positivas de tu vida, que pueden ser el resultado del azar, el destino o tus propias acciones.",
    "cell80":"Sentirse equilibrado puede provenir de una vida bien gestionada donde tus necesidades físicas, emocionales, sociales y espirituales están en armonía.",
    "cell81":"El desaliento puede surgir cuando enfrentas continuos obstáculos o fracasos en tus intentos por alcanzar objetivos importantes, lo que puede minar tu confianza y esperanza.",
    "cell82":"La depresión puede ser desencadenada por una variedad de factores, incluyendo problemas bioquímicos, eventos traumáticos, estrés crónico o acumulación de pequeñas frustraciones.",
    "cell83":"Estar huraño puede ser una reacción a sentirse incomprendido, aislado o descontento con las interacciones sociales, llevando a un retiro y una actitud desconfiada o reservada hacia otros.",
    "cell84":"La exhaustividad a menudo resulta de esfuerzos prolongados o estrés, ya sea físico, mental o emocional, sin suficiente tiempo o recursos para recuperarse adecuadamente.",
    "cell85":"Similar a la exhaustividad, la fatiga puede surgir de sobrecargas prolongadas de trabajo, responsabilidades o incluso falta de estímulos motivadores, dejándote sentir física y emocionalmente drenado.",
    "cell86":"La apacibilidad se experimenta cuando te encuentras en un estado de calma profunda, a menudo como resultado de un ambiente tranquilo o de la ausencia de conflictos.",
    "cell87":"La reflexión surge cuando te tomas el tiempo para contemplar tus pensamientos, experiencias pasadas, o las circunstancias actuales, evaluando y considerando diferentes aspectos de tu vida.",
    "cell88":"La paz interior suele estar relacionada con la aceptación de uno mismo, la resolución de conflictos internos o la armonía con el entorno.",
    "cell89":"Sentirse cómodo puede provenir de una buena salud, seguridad financiera, o relaciones estables y amorosas.",
    "cell90":"La desenfado suele ser el resultado de no tomar las cosas demasiado en serio o de mantener una actitud relajada ante la vida, especialmente en situaciones que podrían considerarse estresantes.",
    "cell91":"Sentirse devastado suele resultar de enfrentar una pérdida significativa o un evento traumático que parece alterar profundamente tu vida o tus expectativas sobre el futuro.",
    "cell92":"La desesperanza puede surgir cuando sientes que tus circunstancias son incontrolables o que las posibilidades de mejorar tu situación son mínimas o nulas.",
    "cell93":"El sentimiento de desolación puede ocurrir después de experimentar una decepción profunda o cuando sientes que has perdido algo esencial para tu felicidad o sentido de identidad.",
    "cell94":"Sentirse consumido es común cuando estás abrumado por preocupaciones, responsabilidades o emociones negativas que parecen agotar tus recursos mentales o físicos.",
    "cell95":"El agotamiento puede resultar no solo de la carga de trabajo o actividad excesiva, sino también de la falta de estímulos emocionales y motivacionales que sustenten el esfuerzo.",
    "cell96":"El sentirse soñoliento puede ser una señal de que tu cuerpo y mente necesitan descansar, ya sea debido a la actividad física, el esfuerzo mental, o simplemente como parte de tu ciclo normal de sueño.",
    "cell97":"Sentirse complaciente puede ser resultado de estar en una situación confortable donde tus necesidades están siendo cumplidas sin necesidad de esfuerzo adicional.",
    "cell98":"La tranquilidad puede venir de un sentido de seguridad, una falta de conflictos inmediatos o desafíos, o una satisfacción general con la vida.",
    "cell99":"Ser afable generalmente surge de sentirse bien contigo mismo y con los demás, y puede ser resultado de una personalidad naturalmente amigable o de una serie de interacciones sociales positivas.",
    "cell100":"La serenidad a menudo proviene de una profunda aceptación de la vida tal y como es, sin deseo de cambio inmediato o lucha contra las circunstancias actuales."
}
var funciones = {
    "cell1":"Sentirse enfurecido puede ser un motor para el cambio, proporcionando la energía necesaria para abordar y rectificar injusticias o problemas.",
    "cell2":"El terror te prepara para la huida rápida, aumentando tus niveles de alerta y capacidad de respuesta frente a amenazas potenciales.",
    "cell3":"El estrés puede motivarte a resolver los problemas que causan dicha tensión, potenciando la búsqueda de soluciones efectivas.",
    "cell4":"Esta emoción te mantiene alerta y preparado para reaccionar ante posibles cambios o desafíos inminentes.",
    "cell5":"Esta emoción te ayuda a reconocer la magnitud de un evento y a movilizar recursos emocionales y cognitivos para enfrentarlo.",
    "cell6":"Esta emoción aumenta la alerta y la atención, preparando al cerebro para procesar y responder a nuevas circunstancias.",
    "cell7":"Esta emoción refuerza las relaciones sociales y aumenta el bienestar personal al apreciar y valorar lo que te rodea.",
    "cell8":"Promueve la cohesión comunitaria y el disfrute colectivo, fortaleciendo lazos sociales y creando recuerdos positivos.",
    "cell9":"Esta intensa felicidad puede motivarte a alcanzar mayores logros y a perseguir experiencias que te aporten significado y satisfacción.",
    "cell10":"Esta emoción profundiza el aprecio por la vida y sus posibilidades, intensificando la experiencia de vivir y la conexión con lo que te rodea.",
    "cell11":"Esta emoción subraya la gravedad de un problema, impulsándote a buscar soluciones alternativas o ayuda externa.",
    "cell12":"Sirve como un mecanismo de defensa para proteger tus valores y establecer límites claros.",
    "cell13":"La frustración señala la necesidad de reevaluar tus estrategias o esfuerzos, incentivando la búsqueda de nuevas soluciones o enfoques.",
    "cell14":"Esta emoción te prepara para actuar eficientemente bajo presión, mejorando tu enfoque y capacidad de respuesta.",
    "cell15":"Esta emoción te hace pausar y evaluar la nueva información, permitiéndote adaptar tu modelo mental a las circunstancias.",
    "cell16":"Esta emoción potencia la productividad y la creatividad, permitiéndote realizar tareas con una energía y velocidad excepcionales.",
    "cell17":"Fomenta la conexión social y el bienestar compartido, mejorando las relaciones y creando un ambiente positivo.",
    "cell18":"Impulsa la acción dirigida hacia metas, proporcionando la energía y el enfoque necesarios para lograr objetivos personales o profesionales.",
    "cell19":"Alimenta la creatividad y el desarrollo personal, incentivando la exploración de nuevas ideas y proyectos.",
    "cell20":"Esta emoción intensifica las experiencias de logro y éxito, fortaleciendo tu autoestima y confianza en tus capacidades.",
    "cell21":"Esta emoción intensifica tu deseo de resolver una situación frustrante, impulsándote a buscar cambios significativos.",
    "cell22":"Estar asustado te prepara para reaccionar rápidamente a situaciones peligrosas, ya sea para huir o para defenderte.",
    "cell23":"Esta emoción puede motivarte a tomar medidas para cambiar situaciones que consideras injustas o insatisfactorias.",
    "cell24":"Esta emoción te mantiene alerta y puede mejorar tu rendimiento al prepararte para posibles complicaciones.",
    "cell25":"La inquietud puede incitarte a buscar nuevas experiencias o soluciones, impulsando el crecimiento personal y profesional.",
    "cell26":"Esta emoción provee la vitalidad necesaria para emprender actividades y cumplir con las demandas diarias, promoviendo la eficiencia y el entusiasmo en tus acciones.",
    "cell27":"Fomenta la sociabilidad y el disfrute, creando un ambiente amigable y acogedor tanto para uno mismo como para los demás.",
    "cell28":"Activa y prepara tu mente y cuerpo para nuevas experiencias, potenciando la atención y la memoria asociada a estos eventos.",
    "cell29":"Proporciona resiliencia emocional, ayudándote a enfrentar desafíos con una actitud positiva y a recuperarte de contratiempos con mayor facilidad.",
    "cell30":"Impulsa la dedicación y el compromiso con las actividades que te apasionan, proporcionando la motivación necesaria para perseguir tus intereses con energía y dedicación.",
    "cell31":"La ansiedad te ayuda a prepararte para enfrentar posibles desafíos, aumentando tu nivel de alerta y capacidad para responder a amenazas percibidas.",
    "cell32":"Esta emoción te impulsa a ser cauteloso y a evaluar cuidadosamente los riesgos antes de tomar decisiones.",
    "cell33":"La preocupación puede ser un estímulo para la planificación y preparación, ayudándote a anticipar y mitigar posibles problemas.",
    "cell34":"Te alerta sobre pequeñas discrepancias o problemas que necesitan ajuste, ayudando a mantener tus estándares o límites personales.",
    "cell35":"El enojo motiva a la acción, puede ser un catalizador para resolver problemas, defender tus derechos y establecer límites claros.",
    "cell36":"Esta emoción refuerza comportamientos y decisiones que te llevan a resultados satisfactorios, incentivando la repetición de acciones que generan felicidad y contento",
    "cell37":"Facilita la toma de decisiones claras y coherentes, mejora la concentración y permite manejar el estrés de manera efectiva.",
    "cell38":"Promueve un sentido de bienestar general y puede mejorar la salud física y mental, además de fortalecer las relaciones sociales.",
    "cell39":"Motiva a mantener o mejorar tus estándares y comportamientos, y puede servir como un ejemplo inspirador para otros.",
    "cell40":"Estimula la planificación y la acción hacia metas futuras, proporcionando un sentido de propósito y dirección.",
    "cell41":"Funciona como un llamado a la acción contra las injusticias, motivando a defender principios éticos o morales.",
    "cell42":"Esta emoción permite un proceso de duelo necesario para aceptar y eventualmente superar las pérdidas.",
    "cell43":"Esta emoción resalta la importancia de lo sucedido, motivándote a prestar atención y reaccionar a las circunstancias.",
    "cell44":"Incita a la revisión y reconsideración de tus planes y acciones, propiciando una preparación más adecuada.",
    "cell45":"Esta emoción sirve como un indicador de que algo necesita ser abordado o ajustado en tu entorno o interacciones.",
    "cell46":"Esta emoción mejora la disposición social y fomenta relaciones positivas, haciendo que tanto uno mismo como los demás se sientan bienvenidos y valorados.",
    "cell47":"Promueve un optimismo saludable y reduce el estrés, lo cual puede llevar a una mejor salud física y emocional.",
    "cell48":"Esta emoción proporciona resiliencia en tiempos difíciles y motiva a seguir adelante a pesar de los obstáculos o desafíos.",
    "cell49":"Esta emoción estimula la creatividad, la innovación y el aprendizaje, y puede fortalecer las relaciones a través de la interacción lúdica y divertida.",
    "cell50":"El estado de dicha profundiza el aprecio por la vida y puede proporcionar una renovada pasión y entusiasmo por futuras experiencias.",
    "cell51":"El rechazo te alerta sobre la importancia de las relaciones sociales y puede motivarte a reflexionar sobre tus interacciones y cómo mejorarlas.",
    "cell52":"Esta emoción puede ser una forma de procesamiento interno, permitiendo que reflexiones y consideres tus pensamientos y sentimientos más profundamente.",
    "cell53":"Te ayuda a reevaluar tus expectativas y a adaptarte a la realidad de la situación, fomentando un enfoque más realista y resiliente.",
    "cell54":"Esta emoción puede servir como un indicativo de que necesitas descansar y recuperarte emocional y físicamente.",
    "cell55":"Actúa como una señal de que puede ser necesario reevaluar tus compromisos y encontrar nuevas formas de reengancharse y encontrar significado.",
    "cell56":"Promueve el bienestar general y puede ayudar a mantener una actitud positiva y una salud mental equilibrada.",
    "cell57":"Ayuda a recargar tus energías mentales y emocionales, proporcionando un descanso necesario de las tensiones cotidianas.",
    "cell58":"Reconoce y valida tus esfuerzos y experiencias positivas, lo que puede fortalecer tu autoestima y sentido de la felicidad.",
    "cell59":"Fomenta vínculos sociales fuertes y una sensación de conexión con el mundo que te rodea, lo que es esencial para el bienestar emocional.",
    "cell60":"Valida tus esfuerzos y decisiones, reforzando el sentido de propósito en tu vida y alentándote a seguir adelante con tus pasiones y objetivos.",
    "cell61":"Esta emoción puede funcionar como un mecanismo de defensa, preparándote para el peor escenario y posiblemente protegiéndote de desilusiones.",
    "cell62":"Esta emoción puede ser una señal para que prestes atención a tus necesidades básicas o emocionales y tomes medidas para cuidarte mejor.",
    "cell63":"Puede servir para hacerte tomar un descanso y reevaluar tus métodos o estrategias, buscando un enfoque más efectivo.",
    "cell64":"Te permite procesar y reflexionar sobre experiencias dolorosas o significativas, facilitando eventualmente la aceptación y el crecimiento personal.",
    "cell65":"Este sentimiento puede motivarte a buscar nuevas experiencias y desafíos que enriquezcan tu vida y expandan tus horizontes.",
    "cell66":"Facilita la claridad mental y la estabilidad emocional, permitiendo un enfoque más efectivo y una toma de decisiones reflexiva.",
    "cell67":"Este sentimiento fomenta la toma de riesgos calculados y el crecimiento personal, ya que te sientes apoyado y confiado en tus capacidades.",
    "cell68":"Te proporciona un sentido de logro y plenitud, y puede ser un motivador para continuar en la búsqueda de metas y experiencias enriquecedoras.",
    "cell69":"Fortalece las relaciones sociales y mejora el bienestar emocional al enfocarse en lo positivo y en la generosidad de otros.",
    "cell70":"Esta emoción puede inspirar actos de generosidad y conectar profundamente con los demás y con la condición humana en general.",
    "cell71":"Esta emoción puede ser una señal para reevaluar tus conexiones y entornos, motivándote a buscar relaciones o grupos más afines a tus valores personales.",
    "cell72":"Actúa como un indicador de que tus necesidades emocionales o físicas no están siendo satisfechas, sugiriendo la necesidad de cambios o ajustes en tu vida.",
    "cell73":"Fomenta una introspección sobre tus metas y estrategias, posiblemente señalando la necesidad de un nuevo enfoque o renovación del compromiso.",
    "cell74":"Promueve el crecimiento personal y emocional al permitirte enfrentar y procesar eventos o situaciones difíciles.",
    "cell75":"Puede ser un impulso para que explores nuevas áreas de interés o te involucres en desafíos más significativos y enriquecedores.",
    "cell76":"Facilita la recuperación física y mental, disminuye el estrés y mejora el bienestar general.",
    "cell77":"Ayuda a mantener un estado de ánimo equilibrado y promueve la flexibilidad mental y física.",
    "cell78":"Te permite recuperarte de la fatiga y restaurar tu energía para las tareas y desafíos que tienes por delante.",
    "cell79":"Refuerza la percepción de que la vida es generosa y llena de regalos inesperados, lo cual puede aumentar tu sensación de gratitud y felicidad.",
    "cell80":"Proporciona una base sólida para el crecimiento personal y la capacidad de manejar los altibajos de la vida con gracia.",
    "cell81":"Esta emoción puede servir como un indicativo para revisar y posiblemente ajustar tus expectativas o métodos, buscando formas más efectivas de alcanzar tus metas.",
    "cell82":"Más que servir un propósito adaptativo obvio, la depresión puede indicar que necesitas hacer cambios significativos en tu vida, buscar ayuda profesional, o ajustar tus estrategias de afrontamiento.",
    "cell83":"Esta emoción puede protegerte de heridas emocionales adicionales mientras evaluas y posiblemente reconfiguras tus relaciones y entornos sociales.",
    "cell84":"Indica la necesidad de descanso y recuperación, subrayando la importancia de gestionar tus recursos personales de manera sostenible.",
    "cell85":"Esta emoción te alerta sobre la necesidad de equilibrar tus actividades y responsabilidades con suficiente tiempo de descanso y recuperación.",
    "cell86":"Contribuye a un estado mental sereno, facilitando el pensamiento claro y una actitud compasiva hacia uno mismo y hacia los demás.",
    "cell87":"Permite el aprendizaje y el crecimiento personal, y puede ayudar a resolver problemas o conflictos internos.",
    "cell88":"Brinda una sensación de satisfacción y tranquilidad que no se perturba fácilmente por el estrés o la adversidad externa.",
    "cell89":"Promueve una sensación de seguridad y satisfacción con las circunstancias de tu vida.",
    "cell90":"Ayuda a mantener el estrés a raya y puede promover una interacción social positiva y despreocupada.",
    "cell91":"Esta intensa emoción refleja la magnitud del impacto de un evento en tu vida y puede servir como un punto de partida para el proceso de duelo y eventual recuperación.",
    "cell92":"Aunque dolorosa, esta emoción puede ser una señal para que reconsideres y busques nuevas formas de abordar tus problemas desde diferentes ángulos o con ayuda externa.",
    "cell93":"Esta emoción subraya la necesidad de reevaluar lo que es fundamental para tu bienestar y quizás de buscar nuevos significados o direcciones en la vida.",
    "cell94":"Indica la necesidad de hacer un alto, reevaluar tus compromisos y cuidar mejor de tu salud mental y física.",
    "cell95":"Alerta sobre la insostenibilidad de tu estilo de vida actual y la necesidad de introducir cambios para preservar tu energía y salud a largo plazo.",
    "cell96":"El sueño cumple una función vital en la reparación y recuperación del cuerpo y la mente, permitiendo un mejor desempeño y bienestar.",
    "cell97":"Puede servir como un estado de aceptación y satisfacción con las cosas tal y como son, sin buscar cambio o mejoramiento.",
    "cell98":"Ayuda a preservar la energía y mantener una actitud positiva, lo cual es beneficioso para tu salud mental y física a largo plazo.",
    "cell99":"Esta amabilidad facilita las interacciones sociales y puede contribuir a construir y mantener relaciones sólidas y gratificantes.",
    "cell100":"Promueve la estabilidad emocional y una profunda sensación de paz interior, lo que puede ser beneficioso en tiempos de estrés o cambio.",
}
var consejos = {
    "cell1":"Toma un momento para respirar profundamente y contar hasta diez antes de reaccionar.<br><br>Expresa tus sentimientos de manera constructiva, enfocándote en explicar el porqué te sientes enfurecido sin atacar a los demás.<br><br>Realiza una actividad física para canalizar la energía acumulada y reducir la intensidad de tu enfado.",
    "cell2":"Reconoce y acepta el miedo como una señal de que algo importante está en juego.<br><br>Practica técnicas de relajación como la respiración profunda o la meditación para calmar tu mente.<br><br>Habla sobre tus miedos con alguien de confianza para obtener perspectiva y apoyo.",
    "cell3":"Organiza tu tiempo y responsabilidades para gestionar mejor las causas de tu estrés.<br><br>Dedica tiempo a actividades que disfrutes y que te relajen para equilibrar tus niveles de estrés.<br><br>Busca apoyo en amigos, familiares o profesionales que puedan ofrecerte consejo o asistencia.",
    "cell4":"Mantén una rutina diaria que incluya periodos de descanso y actividad para minimizar la sensación de inquietud.<br><br>Prueba técnicas de mindfulness para estar presente y reducir pensamientos anticipatorios.<br><br>Establece pequeñas metas diarias para sentir un mayor control sobre tu vida.",
    "cell5":"Permite que tus sentimientos fluyan y acéptalos como parte de tu proceso de ajuste a la nueva realidad.<br><br>Busca apoyo en tu comunidad o círculo social para compartir experiencias y recuperarte.<br><br>Cuando estés listo, intenta volver gradualmente a tus actividades habituales para restablecer la normalidad.",
    "cell6":"Aprovecha la energía inicial de la sorpresa para explorar y aprender de la nueva situación.<br><br>Comparte tu experiencia con otros, lo que puede enriquecer tu comprensión del evento.<br><br>Utiliza la sorpresa como una oportunidad para adaptarte y ser más flexible en tus pensamientos y acciones.",
    "cell7":"Cultiva un entorno que te permita experimentar momentos de encanto con regularidad.<br><br>Sé consciente y agradecido por los momentos que te proporcionan este sentimiento.<br><br>Comparte tus experiencias encantadoras con otros para multiplicar el efecto positivo.",
    "cell8":"Participa activamente en las festividades y contribuye a crear un ambiente alegre.<br><br>Aprovecha estos momentos para fortalecer relaciones y conocer nuevas personas.<br><br>Recuerda moderar los excesos para mantener las celebraciones saludables y seguras.",
    "cell9":"Utiliza la energía de la euforia para establecer nuevos objetivos y desafíos.<br><br>Comparte tu alegría y tus logros con otros para inspirar y elevar a quienes te rodean.<br><br>Mantén un enfoque equilibrado para no depender exclusivamente de altos emocionales para tu bienestar.",
    "cell10":"Canaliza la energía del éxtasis hacia actividades creativas o productivas.<br><br>Toma tiempo para reflexionar sobre la experiencia y aprender de ella.<br><br>Asegúrate de compartir tus experiencias extáticas para enriquecer tus relaciones personales.",
    "cell11":"Enfócate en soluciones paso a paso y celebra los pequeños logros para reducir la sensación de desesperanza.<br><br>Expande tu red de soporte buscando personas que hayan enfrentado situaciones similares.<br><br>Considera la asistencia de un profesional si la desesperación se siente abrumadora.",
    "cell12":"Usa la escritura o la conversación para expresar tus sentimientos sin causar daño a otros.<br><br>Practica técnicas de relajación como la respiración profunda o la meditación para calmar la intensidad emocional.<br><br>Trabaja en identificar el origen de tu furia para abordarlo de manera más efectiva.",
    "cell13":"Toma un descanso para alejarte de la situación y regresar con una nueva perspectiva.<br><br>Establece metas más realistas o divide grandes tareas en pasos más pequeños y manejables.<br><br>Comunica tus sentimientos y expectativas claramente a quienes te rodean para obtener apoyo o ajustar responsabilidades.",
    "cell14":"Practica técnicas de relajación, como yoga o tai chi, que ayudan a liberar la tensión corporal.<br><br>Organiza tu entorno y tu tiempo para reducir las fuentes de estrés.<br><br>Asegúrate de dormir suficiente y mantener una alimentación balanceada para apoyar tu bienestar físico.",
    "cell15":"Permítete tiempo para procesar lo que ha sucedido antes de tomar cualquier acción.<br><br>Discute tus pensamientos y sentimientos con otros para obtener diferentes perspectivas.<br><br>Mantén una mente abierta para integrar nueva información de manera efectiva.",
    "cell16":"Canaliza la energía extra en actividades productivas o físicas que requieran movimiento y esfuerzo.<br><br>Establece momentos para calmar y equilibrar tu energía, como técnicas de respiración o meditación.<br><br>Asegúrate de no sobrecargarte tomando más tareas de las que puedes manejar de manera sostenible.",
    "cell17":"Participa y fomenta encuentros sociales que nutran tu espíritu jovial.<br><br>Comparte tu alegría con otros, contagiando tu buen humor y positividad.<br><br>Mantén una perspectiva equilibrada para que esta disposición alegre no minimice o ignore situaciones serias cuando se presenten.",
    "cell18":"Establece metas claras y desafiantes que sean realistas y medibles.<br><br>Celebra los pequeños logros en el camino hacia tus metas más grandes para mantener la motivación.<br><br>Rodea de personas o ambientes que apoyen y refuercen tu impulso hacia el éxito.",
    "cell19":"Toma nota de lo que te inspira y busca activamente estas fuentes de inspiración regularmente.<br><br>Dedica tiempo para desarrollar tus ideas creativas en proyectos concretos.<br><br>Comparte tus inspiraciones con otros, lo que puede ampliar tu impacto y el de tus ideas.",
    "cell20":"Utiliza la energía de la exultación para fijar nuevas metas y desafíos futuros.<br><br>Comparte tus éxitos con aquellos que te apoyaron, reconociendo su parte en tus logros.<br><br>Reflexiona sobre el camino que te llevó al éxito para entender y replicar tus fortalezas en futuras empresas.",
    "cell21":"Identifica las causas subyacentes de tu exasperación para tratarlas directamente.<br><br>Pide ayuda o colaboración para abordar problemas complejos.<br><br>Practica la paciencia y el reconocimiento de tus esfuerzos, aun cuando los resultados no sean inmediatos.",
    "cell22":"Practica técnicas de respiración para calmar el sistema nervioso.<br><br>Enfréntate gradualmente a tus miedos en un entorno controlado para reducir su impacto.<br><br>Mantén un diálogo interno positivo para reforzar tu capacidad de manejar situaciones difíciles.",
    "cell23":"Aprende a identificar los desencadenantes de tu enojo para poder evitarlos o enfrentarlos mejor.<br><br>Exprésate de manera constructiva, usando \"yo siento\" para describir tus emociones sin culpar a otros.<br><br>Encuentra formas de canalizar tu enojo en acciones productivas o creativas.",
    "cell24":"Prepara meticulosamente para eventos o situaciones que te ponen nervioso.<br><br>Utiliza visualizaciones positivas para aumentar tu confianza.<br><br>Practica la meditación o ejercicios de relajación para mantener la calma.",
    "cell25":"Establece metas claras y pasos prácticos para alcanzarlas.<br><br>Incorpora nuevas actividades o hobbies en tu rutina para satisfacer tu necesidad de cambio.<br><br>Reflexiona sobre tus logros y recalibra tus expectativas si es necesario.",
    "cell26":"Aprovecha los picos de energía para abordar tareas importantes o desafiantes.<br><br>Mantén un equilibrio saludable entre actividad y descanso para no agotar tu energía.<br><br>Incorpora una rutina regular de ejercicio físico para mantener y mejorar tus niveles de energía.",
    "cell27":"Cultiva relaciones y participa en actividades que refuercen estos sentimientos positivos.<br><br>Expresa abiertamente tu entusiasmo para contagiar a otros y fortalecer la dinámica grupal.<br><br>Utiliza esta energía para impulsar proyectos creativos o eventos sociales.",
    "cell28":"Mantén expectativas realistas para evitar decepciones si las cosas no resultan exactamente como anticipaste.<br><br>Comparte tu emoción con amigos o familiares para enriquecer la experiencia a través de la conexión social.<br><br>Canaliza tu energía emocional hacia la preparación o planificación de los detalles de la próxima experiencia.",
    "cell29":"Cultiva una mentalidad de crecimiento, viendo los desafíos como oportunidades para aprender y mejorar.<br><br>Practica la gratitud diariamente para reforzar una visión positiva de tu vida y circunstancias.<br><br>Rodeate de influencias y personas que refuercen tu optimismo.",
    "cell30":"Canaliza tu entusiasmo hacia metas y proyectos productivos que te permitan crecer y tener éxito.<br><br>Asegúrate de planificar y organizar tus recursos para mantener sostenible tu impulso.<br><br>Comparte tu pasión con otros para inspirar y motivar, creando una red de apoyo mutuo.",
    "cell31":"Practica técnicas de relajación y respiración para reducir la tensión física y mental.<br><br>Enfócate en lo que puedes controlar y deja de lado las preocupaciones sobre lo que no puedes.<br><br>Habla sobre tus preocupaciones con alguien de confianza o un profesional para obtener apoyo y consejos.",
    "cell32":"Analiza objetivamente los riesgos y beneficios de la situación que te preocupa.<br><br>Desarrolla un plan de acción para los posibles escenarios, lo que puede ayudar a reducir la aprensión.<br><br>Fortalece tu confianza en ti mismo a través de pequeños éxitos en situaciones similares.",
    "cell33":"Escribe tus preocupaciones para organizar tus pensamientos y determinar acciones concretas.<br><br>Limita el tiempo que dedicas a preocuparte cada día, permitiendo solo momentos específicos para ello.<br><br>Engáñate en actividades relajantes o deportivas para desviar tu atención de las preocupaciones.",
    "cell34":"Tómate un momento para reflexionar si la causa de la irritación realmente amerita una reacción fuerte.<br><br>Práctica la paciencia y el entendimiento, especialmente en interacciones con otros.<br><br>Aprende a comunicar tus molestias de manera asertiva y respetuosa, sin dejar que se acumulen.",
    "cell35":"Practica la pausa consciente antes de responder, lo que te permite manejar tus reacciones de manera más controlada.<br><br>Utiliza técnicas de comunicación asertiva para expresar tus necesidades y sentimientos sin agredir.<br><br>Canaliza tu enojo hacia actividades productivas como el ejercicio, lo cual",
    "cell36":"Toma tiempo para reconocer y apreciar los momentos y resultados que te han hecho sentir complacido.<br><br>Comparte tus experiencias positivas con otros, lo que puede también mejorar sus estados de ánimo y fortalecer las relaciones.<br><br>Utiliza este sentimiento como motivación para establecer y alcanzar nuevas metas que puedan producir satisfacción similar.",
    "cell37":"Practica técnicas de mindfulness y meditación regularmente para mantener y fortalecer este estado de centrado.<br><br>Mantén un diario de reflexiones personales para explorar y afirmar tus valores y objetivos.<br><br>Asegúrate de que tus actividades diarias y tus relaciones estén alineadas con tus principios fundamentales.",
    "cell38":"Cultiva la gratitud por las cosas pequeñas y grandes en tu vida.<br><br>Dedica tiempo a actividades y relaciones que te hacen sentir feliz.<br><br>Busca compartir tu felicidad con otros, lo cual puede amplificar tus propias experiencias positivas.",
    "cell39":"Celebra tus logros de manera que reconozca el esfuerzo y la dedicación requeridos.<br><br>Comparte el crédito con aquellos que te han ayudado a alcanzar tus logros.<br><br>Utiliza el orgullo como un motivador para establecer futuros objetivos, manteniendo una perspectiva humilde y constructiva.",
    "cell40":"Establece metas claras y pasos concretos hacia tus visiones y sueños.<br><br>Comparte tus ilusiones con otros para obtener apoyo y posiblemente nuevas ideas.<br><br>Mantén un equilibrio entre tus sueños futuros y el disfrute del presente, asegurando un bienestar integral.",
    "cell41":"Evalúa si tu respuesta puede contribuir a una solución efectiva antes de actuar.<br><br>Canaliza tu energía hacia causas constructivas o activismo.<br><br>Mantén el diálogo y busca apoyos para tus causas en comunidades o redes sociales.",
    "cell42":"Permítete sentir y expresar la tristeza sin juzgarte.<br><br>Busca apoyo en amigos, familiares o grupos de apoyo que puedan entender y acompañar tu dolor.<br><br>Encuentra formas saludables de conmemorar y recordar aquello que has perdido, lo que puede facilitar la sanación emocional.",
    "cell43":"Tómate el tiempo necesario para procesar los eventos y sus efectos sobre ti.<br><br>Habla sobre tus experiencias y emociones con personas de confianza para aliviar la carga emocional.<br><br>Si es necesario, busca ayuda profesional para desarrollar estrategias de afrontamiento y adaptación.",
    "cell44":"Dedica tiempo a la planificación y organización para abordar las causas de tu inquietud.<br><br>Realiza actividades que fomenten la calma y la concentración, como el yoga o la meditación.<br><br>Establece prioridades claras y maneja tu tiempo y recursos de manera efectiva para reducir la ansiedad.",
    "cell45":"Identifica específicamente qué está causando tu molestia y considera formas de comunicarlo efectivamente.<br><br>Establece límites claros y respetuosos con aquellos que influyen en tu estado emocional.<br><br>Practica técnicas de autocontrol emocional para manejar mejor tus reacciones en situaciones frustrantes.",
    "cell46":"Busca y crea activamente entornos que fomenten sensaciones agradables.<br><br>Practica la empatía y la cortesía en tus interacciones diarias para perpetuar y expandir esta sensación.<br><br>Reflexiona sobre las cosas que te hacen sentir a gusto y trabaja para incorporar más de esas experiencias en tu vida diaria.",
    "cell47":"Involúcrate en actividades que conoces que te traerán alegría de manera regular.<br><br>Comparte tus momentos de alegría con otros para fortalecer tus conexiones sociales.<br><br>Mantén una actitud de apertura a nuevas experiencias que puedan traerte felicidad.",
    "cell48":"Cultiva una visión clara y positiva del futuro, incluso en circunstancias difíciles.<br><br>Establece metas realistas y pasos prácticos para alcanzarlas, manteniendo la esperanza viva.<br><br>Rodeate de personas y recursos que refuercen tu optimismo y te apoyen en tus esfuerzos.",
    "cell49":"Dedica tiempo regularmente para actividades lúdicas, tanto solo como con amigos o familiares.<br><br>Alienta un entorno donde el juego y la exploración sean valorados y fomentados.<br><br>Usa el humor y la diversión como herramientas para mejorar tanto tu estado de ánimo como el de los demás.",
    "cell50":"Toma conciencia de los momentos en los que te sientes especialmente dichoso para entender qué los provoca.<br><br>Trata de replicar o buscar situaciones similares que generen dicha en tu vida.<br><br>Comparte tus experiencias de dicha con otros, potenciando así tu propia felicidad y la de las personas a tu alrededor."
    ,
    "cell51":"Acepta que el rechazo es una parte normal de las relaciones humanas y no refleja tu valor como persona.<br><br>Busca apoyo en amigos y familiares que te valoren y acepten.<br><br>Reflexiona sobre cualquier aprendizaje que puedas extraer de la experiencia para mejorar tus futuras interacciones sociales.",
    "cell52":"Permite que este tiempo de silencio sirva para una reflexión constructiva.<br><br>Si te sientes atrapado en pensamientos negativos, trata de realizar actividades que estimulen tu mente de manera positiva.<br><br>Comparte tus pensamientos con alguien de confianza si te sientes abrumado o necesitas una perspectiva externa.",
    "cell53":"Ajusta tus expectativas para futuras situaciones basándote en experiencias previas.<br><br>Expresa tus sentimientos de decepción de manera constructiva para evitar malentendidos.<br><br>Encuentra formas de recuperarte y seguir adelante, enfocándote en nuevas oportunidades.",
    "cell54":"Tómate un tiempo para descansar y participar en actividades que rejuvenezcan tu espíritu.<br><br>Mantén una rutina de ejercicio moderado y una dieta equilibrada para ayudar a mejorar tu estado de ánimo.<br><br>Considera hablar con un profesional si sientes que el estado decaído persiste y afecta tu capacidad para funcionar diariamente.",
    "cell55":"Identifica las áreas de tu vida donde sientes más apatía y considera cambios que podrían revitalizar tu interés.<br><br>Establece metas pequeñas y alcanzables para ayudar a restaurar el sentido de logro.<br><br>Si la apatía es severa o prolongada, buscar la ayuda de un consejero o terapeuta podría ser beneficioso.",
    "cell56":"Reconoce y busca activamente las situaciones que te hacen sentir a gusto para poder recrearlas en el futuro.<br><br>Mantén un entorno ordenado y agradable que refleje tus preferencias personales y promueva la tranquilidad.<br><br>Comparte tu espacio y tiempo con personas que contribuyan a tu sensación de comodidad.",
    "cell57":"Practica técnicas de mindfulness para prolongar los momentos de despreocupación.<br><br>Organiza tu tiempo y responsabilidades para que puedas disfrutar de periodos regulares sin preocupaciones.<br><br>Aprende a delegar tareas y a decir no cuando sea necesario para mantener un equilibrio saludable en tu vida.",
    "cell58":"Toma nota de los momentos o actividades que te hacen sentir contento para recordarlos y apreciarlos.<br><br>Celebra tus éxitos y los momentos felices, por pequeños que sean, para construir una perspectiva positiva de la vida.<br><br>Comparte tu contentamiento con otros; la felicidad compartida se multiplica.",
    "cell59":"Exprésate y demuestra tus sentimientos amorosos a través de actos de bondad y aprecio.<br><br>Cultiva relaciones y dedica tiempo a nutrir los vínculos afectivos en tu vida.<br><br>Reconoce y aprecia el amor en todas sus formas, incluyendo la amistad, el romance y el amor propio.",
    "cell60":"Reflexiona sobre tus logros y reconoce los pasos que te llevaron a sentirte realizado.<br><br>Establece nuevas metas que te desafíen y te permitan crecer aún más.<br><br>Ayuda a otros a encontrar su propio camino hacia la realización, lo que puede ser una fuente de satisfacción aún mayor.",
    "cell61":"Trata de identificar patrones de pensamiento que pueden estar influyendo en tu visión pesimista y desafíalos con evidencia real.<br><br>Practica la gratitud diaria para enfocarte en los aspectos positivos de tu vida.<br><br>Rodéate de personas que tengan una influencia positiva y que te ayuden a ver las situaciones desde diferentes perspectivas.",
    "cell62":"Asegúrate de atender tus necesidades físicas, como el sueño, la alimentación y el descanso.<br><br>Encuentra técnicas de relajación que te ayuden a gestionar el estrés y la irritabilidad.<br><br>Expresa tus sentimientos de manera constructiva antes de que se acumulen y causen explosiones de mal humor.",
    "cell63":"Reflexiona sobre lo que está causando el desánimo y considera si necesitas cambiar tu enfoque o buscar ayuda externa.<br><br>Establece objetivos más pequeños y manejables que te permitan sentir progreso y éxito.<br><br>Habla sobre tus desafíos con alguien de confianza; a veces, simplemente compartir tus luchas puede aliviar el peso del desánimo.",
    "cell64":"Permítete sentir y expresar la tristeza sin juicio.<br><br>Busca el apoyo de amigos, familiares o profesionales que puedan ofrecerte consuelo y guía.<br><br>Participa en actividades que te proporcionen consuelo y alegría, como hobbies, lectura o ejercicio.",
    "cell65":"Explora nuevas actividades o pasatiempos que puedan capturar tu interés y motivación.<br><br>Cambia tu rutina diaria para introducir variedad y nuevos desafíos.<br><br>Considera el aburrimiento como una oportunidad para la introspección y la creatividad, encontrando maneras innovadoras de ocupar tu tiempo.",
    "cell66":"Practica regularmente técnicas de relajación y meditación para promover y mantener un estado de calma.<br><br>Organiza tu entorno y horario para minimizar las fuentes de estrés y maximizar los momentos de paz.<br><br>Asume una perspectiva a largo plazo sobre los problemas para mantener una visión equilibrada y no reaccionar excesivamente ante contratiempos temporales.",
    "cell67":"Refuerza tu seguridad interna cultivando la autoconfianza y la autoeficacia a través de desafíos manejables.<br><br>Mantén redes de apoyo sólidas que te proporcionen una sensación de seguridad y pertenencia.<br><br>Celebra tus éxitos y aprende de tus fracasos para construir una base sólida de experiencias positivas.",
    "cell68":"Reconoce y agradece los aspectos de tu vida que te aportan satisfacción.<br><br>Comparte tus experiencias satisfactorias con otros para inspirar y motivar.<br><br>Fija nuevos objetivos que te permitan sentir una satisfacción continua y evitar la complacencia.",
    "cell69":"Lleva un diario de gratitud para registrar y recordar las cosas por las que estás agradecido.<br><br>Expresa tu gratitud a los demás con palabras y acciones, lo que puede mejorar tus relaciones y el bienestar de todos los involucrados.<br><br>Practica la gratitud incluso en situaciones difíciles, buscando el \"lado bueno\" o las lecciones aprendidas.",
    "cell70":"Permite que los momentos que te conmueven te inspiren a tomar acción y a hacer contribuciones positivas a tu alrededor.<br><br>Comparte tus experiencias con otros; hablar de lo que te ha conmovido puede amplificar el sentimiento y su impacto positivo.<br><br>Busca activamente experiencias que sabes que tienen la capacidad de conmoverte, como el arte, la naturaleza o la participación en causas sociales.",
    "cell71":"Explora nuevas comunidades o grupos que compartan tus intereses y valores.<br><br>Expresa tus sentimientos y necesidades en tus relaciones actuales para buscar un mayor entendimiento y conexión.<br><br>Dedica tiempo a actividades que refuercen tu identidad y autoestima.",
    "cell72":"Identifica las áreas específicas de tu vida que contribuyen a tu infelicidad y considera cambios realistas que puedas realizar.<br><br>Busca apoyo en amigos, familia o profesionales para discutir tus sentimientos y obtener consejos.<br><br>Involúcrate en actividades que te proporcionen sentido y satisfacción.",
    "cell73":"Reevalúa tus expectativas y objetivos para asegurarte de que sean alcanzables y gratificantes.<br><br>Celebra tus pequeños logros para mantener la motivación.<br><br>Considera buscar nuevas fuentes de inspiración y motivación, como un hobby o un nuevo proyecto.",
    "cell74":"No dudes en buscar apoyo emocional de amigos, familia o profesionales.<br><br>Dedica tiempo a actividades que naturalmente elevan tu ánimo, como pasar tiempo al aire libre o realizar ejercicio.<br><br>Permite que el proceso de duelo transcurra sin presionarte a sentirte mejor prematuramente.",
    "cell75":"Considera aprender una nueva habilidad o iniciar un proyecto que capture tu interés y energía.<br><br>Varía tu rutina diaria para incluir nuevas experiencias y personas.<br><br>Evalúa tus pasiones y intereses para redirigir tu tiempo hacia actividades que te resulten más gratificantes.",
    "cell76":"Crea un espacio en tu vida para actividades relajantes, como leer, meditar, o pasear.<br><br>Practica técnicas de respiración consciente para profundizar la sensación de relajación.<br><br>Evita la sobreestimulación, especialmente antes de dormir o en momentos dedicados al descanso.",
    "cell77":"Incorpora el humor y la risa en tu vida diaria, ya que pueden ayudar a mantener un ambiente distendido.<br><br>Dedica tiempo a estar con personas que te hagan sentir relajado y feliz.<br><br>Realiza actividades físicas que sean placenteras y te ayuden a liberar la tensión.",
    "cell78":"Establece una rutina de sueño regular que asegure que obtienes suficientes horas de descanso.<br><br>Tómate breves descansos durante el día para prevenir la acumulación de fatiga.<br><br>Cuida tu entorno de sueño optimizando tu habitación para el descanso, manteniéndola oscura, tranquila y a una temperatura confortable.",
    "cell79":"Practica la gratitud reflexionando sobre las cosas buenas de tu vida, incluso las que parecen pequeñas o cotidianas.<br><br>Comparte tu buena fortuna con otros, ya sea a través de actos de bondad o ayudando a quienes son menos afortunados.<br><br>Mantén una perspectiva equilibrada reconociendo que la suerte a menudo viene acompañada de esfuerzo y preparación.",
    "cell80":"Lleva un estilo de vida equilibrado con una dieta saludable, ejercicio regular y tiempo para el ocio y la socialización.<br><br>Haz chequeos regulares de tu estado de ánimo y nivel de estrés para asegurarte de que mantienes el equilibrio.<br><br>Fomenta la flexibilidad mental practicando la adaptabilidad y la apertura a nuevas experiencias y puntos de vista.",
    "cell81":"Tómate un tiempo para reevaluar tus metas y asegúrate de que sean realistas y alcanzables.<br><br>Busca apoyo y consejo de mentores o amigos que puedan ofrecerte una perspectiva fresca y motivadora.<br><br>Divide tus objetivos en pasos más pequeños y manejables, celebrando cada pequeño éxito en el camino.",
    "cell82":"Considera la posibilidad de buscar ayuda profesional como un psicólogo o psiquiatra.<br><br>Mantén una rutina diaria, incluyendo ejercicio físico regular y una dieta balanceada.<br><br>Establece una red de apoyo social que incluya amigos, familiares o grupos de apoyo.",
    "cell83":"Reflexiona sobre las causas de tu comportamiento huraño para entender mejor tus necesidades y límites.<br><br>Considera maneras de comunicarte de forma más efectiva sobre tus sentimientos y necesidades.<br><br>Expande gradualmente tu círculo social participando en actividades grupales de bajo estrés que fomenten la conexión.",
    "cell84":"Prioriza el descanso y asegúrate de obtener suficiente sueño de calidad.<br><br>Aprende a decir no a compromisos adicionales cuando estás cerca de tu límite de energía.<br><br>Incorpora prácticas de relajación y mindfulness en tu rutina diaria para ayudar a gestionar el estrés.",
    "cell85":"Evalúa y ajusta tu carga de trabajo o tus responsabilidades para reducir la fatiga.<br><br>Asegúrate de que estás alimentándote correctamente y manteniendo una hidratación adecuada.<br><br>Integra actividades que te energicen y te proporcionen rejuvenecimiento, como hobbies o ejercicio.",
    "cell86":"Fomenta la creación de espacios y momentos en tu vida que te inviten a la tranquilidad.<br><br>Participa en prácticas como la meditación o el tai chi, que promueven la paz interior.<br><br>Rodéate de naturaleza o música suave, que puedan ayudarte a mantener una sensación de paz.",
    "cell87":"Dedica tiempo regular para la introspección, como escribir en un diario o realizar caminatas reflexivas.<br><br>Habla sobre tus reflexiones con amigos o familiares, ya que la conversación puede profundizar tu comprensión.<br><br>Mantén una actitud abierta y no juzgues tus pensamientos o emociones para permitir una reflexión genuina y constructiva.",
    "cell88":"Practica la aceptación consciente de las situaciones tal como son, sin resistencia o deseo de cambio.<br><br>Dedica tiempo a actividades que alimenten tu espíritu y promuevan la tranquilidad, como la práctica de yoga o la meditación.<br><br>Cultiva relaciones positivas y evita las situaciones que habitualmente perturban tu paz.",
    "cell89":"Agradece y reconoce los aspectos de tu vida que contribuyen a tu comodidad.<br><br>Asegúrate de que tus elecciones de vida sostienen y mejoran estas condiciones.<br><br>Comparte tu bienestar con otros, ofreciendo hospitalidad o apoyo a quienes puedan beneficiarse de tu comodidad.",
    "cell90":"Mantén una perspectiva humorística y ligera ante los desafíos cotidianos.<br><br>No te preocupes en exceso por cosas que están fuera de tu control.<br><br>Disfruta de las actividades lúdicas y sociales que enfatizan la diversión y el disfrute por sobre el rendimiento o la competencia.",
    "cell91":"Permítete sentir y expresar el dolor sin imponerte un límite de tiempo para \"superarlo\".<br><br>Busca el apoyo de amigos, familiares o profesionales especializados en duelo.<br><br>Encuentra formas saludables de honrar la pérdida o el cambio, como rituales o actividades conmemorativas.",
    "cell92":"Enfócate en pequeñas acciones que puedes tomar para mejorar tu situación, lo que puede ayudar a reconstruir tu sensación de esperanza.<br><br>Considera hablar con un terapeuta o consejero, que puede proporcionar perspectiva y herramientas para lidiar con la desesperanza.<br><br>Mantén un diario de logros, por pequeños que sean, para recordarte a ti mismo que el cambio es posible.",
    "cell93":"Dedica tiempo a reflexionar sobre lo que realmente valoras y cómo puedes reconectar con esos elementos o encontrar nuevos.<br><br>Rodéate de personas que te apoyen y te entiendan, y evita aislarte.<br><br>Participa en actividades que encuentres significativas y gratificantes, aunque inicialmente tengas que forzarte un poco.",
    "cell94":"Prioriza tus tareas y compromisos, delegando o posponiendo lo que no es esencial.<br><br>Implementa técnicas de manejo del estrés, como la meditación, el ejercicio o la terapia.<br><br>Asegúrate de que estás tomando descansos adecuados y dándote espacio para recuperarte.",
    "cell95":"Revisa tus rutinas diarias y asegúrate de que incluyen tiempo para el ocio y el descanso.<br><br>Considera adoptar hábitos de vida más saludables, como una mejor dieta y más actividad física.<br><br>Habla sobre tus sentimientos de agotamiento con supervisores o colegas si es relevante, o busca apoyo emocional de amigos y familiares.",
    "cell96":"Escucha a tu cuerpo y asegúrate de obtener suficiente sueño de calidad cada noche.<br><br>Crea una rutina relajante antes de dormir para ayudarte a desconectarte y prepararte para el descanso.<br><br>Evita la cafeína y los dispositivos electrónicos que emiten luz azul antes de ir a la cama, ya que pueden interferir con tu capacidad para quedarte dormido.",
    "cell97":"Mantén un equilibrio entre la complacencia y el esfuerzo por crecer y mejorar.<br><br>Usa momentos de complacencia para apreciar lo que tienes y para cargar energías para futuros desafíos.<br><br>Evita caer en la trampa de la complacencia que puede llevar a la inacción; sigue estableciendo metas que te motiven y te desafíen.",
    "cell98":"Disfruta conscientemente de los periodos de tranquilidad, ya que estos pueden ser espacios de recarga y reflexión.<br><br>Evita la sobreestimulación manteniendo un ambiente tranquilo en casa y en el trabajo.<br><br>Participa en pasatiempos o actividades que promuevan la serenidad y la paz interior.",
    "cell99":"Practica la amabilidad activa, ofreciendo gestos de amistad y apoyo a quienes te rodean.<br><br>Busca construir conexiones genuinas con los demás, mostrando interés y cuidado por sus vidas y experiencias.<br><br>Reconoce los efectos positivos de tu afabilidad y busca maneras de integrar esta cualidad en todos los aspectos de tu vida.",
    "cell100":"Cultiva la serenidad a través de la práctica regular de la meditación o actividades que promuevan la paz interior.<br><br>Rodéate de belleza natural y arte, ya que pueden inducir y amplificar la sensación de serenidad.<br><br>Cuando te enfrentes a desafíos, recuerda mantener la perspectiva y busca la serenidad en lugar de reaccionar con agitación."
}